from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import asyncio
import json
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from ml_model import predict_anomaly

ADMIN_EMAIL = "roshinipachiyappan404@gmail.com"
EMAIL_SENDER = os.getenv("EMAIL_SENDER", "nexus.ai.observability@gmail.com")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "mock_dummy_password") 

def send_alert_email(status, details=""):
    print(f"\n[EMAIL SYSTEM] Preparing email notification to {ADMIN_EMAIL}...")
    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_SENDER
        msg['To'] = ADMIN_EMAIL
        msg['Subject'] = f"Nexus AI Notification: System {status.capitalize()}"
        
        body = f"""Hello Admin,
        
The Nexus AI Observability platform has recorded a change in infrastructure state.

New Status: {status.upper()}
Details: {details}

This message was generated by the Automated Self-Healing Engine.

- Nexus AI Platform
"""
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        # If the user has not provided a real app password, this will fail and fall back to the except block
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"[EMAIL SYSTEM] SUCCESS: Email delivered to {ADMIN_EMAIL}")
    except Exception as e:
        print(f"[EMAIL SYSTEM] MOCK MODE: Email logged locally (Valid SMTP credentials needed for actual delivery).")
        print(f"|  To: {ADMIN_EMAIL}")
        print(f"|  Subject: System {status.capitalize()}")
        print(f"|  Message: {details}\n")


app = FastAPI(title="DevOps Observability API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TelemetryData(BaseModel):
    cpu_percent: float
    memory_percent: float
    request_latency_ms: float
    error_rate: float

active_connections = []

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    active_connections.append(websocket)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        active_connections.remove(websocket)

async def broadcast_telemetry(data: dict):
    for connection in active_connections:
        await connection.send_text(json.dumps(data))

system_state = {
    "status": "healthy",
    "uptime": time.time(),
    "last_anomaly": None,
    "recovery_actions": []
}

def self_heal():
    action = {"time": time.time(), "action": "Restarted specific pod due to anomaly threshold bridge."}
    system_state["recovery_actions"].append(action)
    system_state["status"] = "healthy"

@app.post("/ingest")
async def ingest_telemetry(data: TelemetryData):
    start_time = time.time()
    data_dict = data.model_dump()
    
    is_anomaly, score = predict_anomaly(data_dict)
    
    response_data = {
        "timestamp": time.time(),
        "metrics": data_dict,
        "is_anomaly": is_anomaly,
        "anomaly_score": float(score),
        "system_status": system_state["status"]
    }
    
    if is_anomaly and system_state["status"] == "healthy":
        system_state["status"] = "degraded"
        system_state["last_anomaly"] = time.time()
        print("--> Critical Anomaly Detected! Executing automated containment protocols.")
        
        # Fire self-healing task in background
        asyncio.create_task(trigger_self_healing(float(score)))
        
    await broadcast_telemetry(response_data)
    
    return {"status": "ok", "inference_time_ms": (time.time() - start_time) * 1000}

async def trigger_self_healing(score):
    system_state["status"] = "self_healing"
    await broadcast_telemetry({"event": "self_healing_started"})
    
    # Send email about detection
    send_alert_email("Degraded", f"An anomaly was detected with ML Score: {score:.3f}. Self-healing initiated.")
    
    # Mocking actual pod restart time
    await asyncio.sleep(4)
    
    # Heal the system
    self_heal()
    await broadcast_telemetry({"event": "self_healing_completed", "actions": system_state["recovery_actions"]})
    
    # Send email about resolution
    send_alert_email("Rectified / Healthy", f"The anomaly has been successfully rectified. Associated pods were restarted and system is back to nominal state.")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
