from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, PlainTextResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
import asyncio
import json
import time
import smtplib
from email.mime.text import MIMEText
import collections
from email.mime.multipart import MIMEMultipart
import os
try:
    from backend.ml_model import predict_anomaly, forecast_cpu
except ImportError:
    from ml_model import predict_anomaly, forecast_cpu

ADMIN_EMAIL = "roshinipachiyappan404@gmail.com"
EMAIL_SENDER = os.getenv("EMAIL_SENDER", "nexus.ai.observability@gmail.com")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "mock_dummy_password") 

def send_alert_email(status, details=""):
    print(f"\n[EMAIL SYSTEM] Preparing email notification to {ADMIN_EMAIL}...")
    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_SENDER
        msg['To'] = ADMIN_EMAIL
        msg['Subject'] = f"Nexus AI Notification: System {status.capitalize()}"
        
        body = f"""Hello Admin,
        
The Nexus AI Observability platform has recorded a change in infrastructure state.

New Status: {status.upper()}

Details: {details}

This message was generated by the Automated Self-Healing Engine.

- Nexus AI Platform
"""
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        # If the user has not provided a real app password, this will fail and fall back to the except block
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"[EMAIL SYSTEM] SUCCESS: Email delivered to {ADMIN_EMAIL}")
    except Exception as e:
        print(f"[EMAIL SYSTEM] MOCK MODE: Email logged locally (Valid SMTP credentials needed for actual delivery).")
        print(f"|  To: {ADMIN_EMAIL}")
        print(f"|  Subject: System {status.capitalize()}")
        print(f"|  Message: {details}\n")


import sys
import subprocess

app = FastAPI(title="DevOps Observability API")

@app.on_event("startup")
def startup_event():
    # Start the simulator in the background so it runs automatically in the cloud
    try:
        simulator_path = os.path.join(os.path.dirname(__file__), 'simulator.py')
        subprocess.Popen([sys.executable, simulator_path])
        print("[SYSTEM] Successfully auto-started simulator in background.")
    except Exception as e:
        print(f"[SYSTEM] Failed to auto-start simulator: {e}")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MOCK_TOKEN = "nexus_secure_token"
security = HTTPBearer()

def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    if credentials.credentials != MOCK_TOKEN:
        raise HTTPException(status_code=401, detail="Invalid token")
    return credentials.credentials

class LoginData(BaseModel):
    username: str
    password: str

@app.post("/api/login")
def login(data: LoginData):
    if data.username == "admin" and data.password == "password":
        return {"token": MOCK_TOKEN}
    raise HTTPException(status_code=401, detail="Invalid credentials")

class TelemetryData(BaseModel):
    service_name: str = "nexus-core"
    cpu_percent: float
    memory_percent: float
    request_latency_ms: float
    error_rate: float
    api_status: str = "Online"
    db_latency_ms: float = 0.0

active_connections = []
cpu_history = collections.deque(maxlen=25)

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, token: str = None):
    if token != MOCK_TOKEN:
        await websocket.close(code=1008)
        return
        
    await websocket.accept()
    active_connections.append(websocket)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        active_connections.remove(websocket)

async def broadcast_telemetry(data: dict):
    for connection in active_connections:
        await connection.send_text(json.dumps(data))

system_state = {
    "status": "healthy",
    "uptime": time.time(),
    "last_anomaly": None,
    "recovery_actions": []
}

def self_heal():
    action = {"time": time.time(), "action": "Restarted specific pod due to anomaly threshold bridge."}
    system_state["recovery_actions"].append(action)
    system_state["status"] = "healthy"

@app.post("/ingest")
async def ingest_telemetry(data: TelemetryData, _ = Depends(verify_token)):
    start_time = time.time()
    data_dict = data.model_dump()
    
    is_anomaly, score = predict_anomaly(data_dict)
    
    cpu_history.append(data_dict["cpu_percent"])
    forecast = forecast_cpu(list(cpu_history), steps=5)
    
    response_data = {
        "timestamp": time.time(),
        "metrics": data_dict,
        "is_anomaly": is_anomaly,
        "anomaly_score": float(score),
        "system_status": system_state["status"],
        "cpu_forecast": forecast
    }
    
    if is_anomaly and system_state["status"] == "healthy":
        system_state["status"] = "degraded"
        system_state["last_anomaly"] = time.time()
        print("--> Critical Anomaly Detected! Executing automated containment protocols.")
        
        # Fire self-healing task in background
        asyncio.create_task(trigger_self_healing(float(score)))
        
    await broadcast_telemetry(response_data)
    
    return {"status": "ok", "inference_time_ms": (time.time() - start_time) * 1000}

async def trigger_self_healing(score):
    system_state["status"] = "self_healing"
    await broadcast_telemetry({"event": "self_healing_started"})
    
    # Send email about detection
    send_alert_email("Degraded", f"An anomaly was detected with ML Score: {score:.3f}. Self-healing initiated.")
    
    # Mocking actual pod restart time
    await asyncio.sleep(4)
    
    # Heal the system
    self_heal()
    await broadcast_telemetry({"event": "self_healing_completed", "actions": system_state["recovery_actions"]})
    
    # Send email about resolution
    send_alert_email("Rectified / Healthy", "The anomaly has been successfully rectified. Associated pods were restarted "
                                            "and system is back to nominal state.")

@app.get("/metrics")
def get_prometheus_metrics():
    # Only expose the latest cpu and memory from the history if present, otherwise 0
    latest_cpu = cpu_history[-1] if cpu_history else 0.0
    
    # Hand-craft Prometheus exposition format
    metrics = []
    metrics.append("# HELP nexus_cpu_percent Last received CPU percentage over all services")
    metrics.append("# TYPE nexus_cpu_percent gauge")
    metrics.append(f"nexus_cpu_percent {latest_cpu}")
    
    metrics.append("# HELP nexus_system_status System health status (1=healthy, 0=degraded)")
    metrics.append("# TYPE nexus_system_status gauge")
    is_healthy = 1 if system_state["status"] == "healthy" else 0
    metrics.append(f"nexus_system_status {is_healthy}")
    
    return PlainTextResponse("\n".join(metrics) + "\n")

@app.get("/")
def serve_dashboard():
    html_path = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'index.html')
    with open(html_path, 'r') as f:
        return HTMLResponse(content=f.read())

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
